---
# roles/chromium/tasks/macos.yml

- name: Install chromium browser
  homebrew_cask:
    name: chromium
    state: present
  tags:
    - chromium

- name: Add to dock
  set_fact:
    dockitems_persist: "{{ dockitems_persist + [ { 'name': 'Chromium', 'path': '/Applications/Chromium.app', 'pos': 8 } ] }}"
  tags:
    - chromium