---
# pre_tasks/check_connection.yml

- name: Check internet connection
  uri:
    url: "https://one.one.one.one"
    return_content: no
    method: HEAD
    timeout: 5
  register: internet_connection
  ignore_errors: true
  tags:
    - always

- name: Set internet connection fact
  set_fact:
    has_internet: "{{ internet_connection is succeeded }}"
  tags:
    - always