---
# pre_tasks/debian.yml

- name: Install package management tools
  package:
    name:
      - aptitude
      - software-properties-common
    state: latest
  notify: apt_update
  become: true
  tags:
    - pre_tasks
    - debian_setup

# Enable passwordless sudo for user
- name: Enable passwordless sudo for user
  community.general.sudoers:
    name: "{{ ansible_env.USER }}"
    user: "{{ ansible_env.USER }}"
    commands: "ALL"
    nopassword: true
    sudoers_path: "/etc/sudoers.d"
    state: present
  become: true
  tags:
    - pre_tasks
    - debian_setup

# Check if .config exists, if not create it
- name: Ensure .config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: 0755
  tags:
    - pre_tasks
    - debian_setup

# Hush the terminal login
- name: Hush the terminal login
  file:
    path: "{{ ansible_env.HOME }}/.hushlogin"
    state: touch
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0600
  tags:
    - pre_tasks
    - debian_setup