---
# pre_tasks/debian.yml

- name: Ensure correct sources.list
  block:
    - name: Add sources.list for debian hosts
      copy:
        src: "{{ ansible_distribution | lower }}_sources.list"
        dest: /etc/apt/sources.list
        backup: yes
      when: ansible_distribution in ["Debian", "Ubuntu", "LinuxMint", "Kali", "Parrot"]
    
    - name: Add Pop!_OS sources.list
      copy:
        src: "pop_os_sources.list"
        dest: /etc/apt/sources.list
        backup: yes
      when: ansible_distribution == "Pop!_OS"
  become: true
  tags:
    - pre_tasks
    - debian_setup

- name: Install package management tools
  package:
    name:
      - aptitude
      - software-properties-common
    state: latest
  notify: apt_update
  become: true
  tags:
    - pre_tasks
    - debian_setup

- name: Upgrade all installed packages to the latest version
  apt:
    upgrade: yes
  notify: apt_update
  become: true
  tags:
    - pre_tasks
    - debian_setup

# Enable passwordless sudo for user
- name: Enable passwordless sudo for user
  ansible.builtin.template:
    src: "user-sudo.j2"
    dest: /etc/sudoers.d/{{ ansible_env['USER'] }}
    mode: 0440
  become: true
  tags:
    - pre_tasks
    - debian_setup

# Check if .config exists, if not create it
- name: Ensure .config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: 0755
  tags:
    - pre_tasks
    - debian_setup

# Hush the terminal login
- name: Hush the terminal login
  file:
    path: "{{ ansible_env.HOME }}/.hushlogin"
    state: touch
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0600
  tags:
    - pre_tasks
    - debian_setup