---
# pre_tasks/homebrew/main.yml

# Set Homebrew prefix based on architecture
- name: Set Homebrew prefix based on architecture
  set_fact:
    homebrew_prefix: >
      {% if mac_arch.stdout == 'arm64' %}
        /opt/homebrew
      {% else %}
        /usr/local
      {% endif %}
  tags:
    - pre_tasks

# Check if Homebrew is installed
- name: Check if Homebrew is installed
  stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: brew_check
  tags:
    - pre_tasks

# Install Homebrew silently if not installed
- name: Install Homebrew
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" < /dev/null
  args:
    executable: /bin/bash
    creates: "{{ homebrew_prefix }}/bin/brew"
  when: not brew_check.stat.exists
  environment:
    NONINTERACTIVE: 1
    # Set Homebrew prefix for Apple Silicon if applicable
    HOMEBREW_PREFIX: "{{ homebrew_prefix }}"
  tags:
    - pre_tasks

# Enable passwordless sudo for homebrew
- name: "Enable passwordless sudo for homebrew"
  ansible.builtin.template:
    src: "user-sudo.j2"
    dest: /private/etc/sudoers.d/{{ ansible_env['USER'] }}
    mode: "0440"
  become: true

# Add Homebrew to PATH in shell profile
- name: Add Homebrew to PATH in .zprofile
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: 'export PATH="{{ homebrew_prefix }}/bin:{{ homebrew_prefix }}/sbin:$PATH"'
    create: yes
    state: present
    insertafter: EOF
  tags:
    - pre_tasks