---
# .dotfiles/main.yml

- name: Internet Connection Check
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Internet Connection Check
      include_tasks: pre_tasks/check_connection.yml
      tags:
        - always

- name: Notify user of no internet connection
  when: not has_internet
  tasks:
    - include_tasks: roles/notifications/tasks/gotify.yml

- name: Dotfiles Configuration
  hosts: localhost
  connection: local
  gather_facts: true
  when: has_internet

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Internet Connection Check
      include_tasks: pre_tasks/check_connection.yml
      tags:
        - always

    - name: Pre-tasks
      include_tasks: pre_tasks/main.yml
      tags:
        - pre_tasks

  # Software to install, uncomment any you wish to skip
  roles:
    - name: system
      tags: system

    - name: zsh
      tags: zsh

    - name: aerospace
      when: ansible_os_family == "Darwin"
      tags: aerospace

    - name: ssh
      tags: ssh

    - name: git
      tags: git

    - name: alacritty
      tags: alacritty

    - name: asciiquarium
      tags: asciiquarium

    - name: neofetch
      tags: neofetch

    - name: bat
      tags: bat

    - name: tmux
      tags: tmux

    - name: python
      tags: python

  #  - name: terraform
  #    tags: terraform

  #  - name: opentofu
  #    tags: opentofu

  #  - name: docker
  #    tags: docker

  #  - name: go
  #    tags: go

  #  - name: php
  #    tags: php

  #  - name: packer
  #    tags: packer

  #  - name: audacity
  #    tags: audacity

  #  - name: autofs
  #    tags: autofs

  #  - name: betterbird
  #    tags: betterbird

  #  - name: chromium
  #    tags: chromium

  #  - name: discord
  #    tags: discord

  #  - name: foliate
  #    tags: foliate

  #  - name: fusion360
  #    tags: fusion360

  #  - name: gimp
  #    tags: gimp

  #  - name: libreoffice
  #    tags: libreoffice

  #  - name: lutris
  #    tags: lutris

  #  - name: raycast
  #    tags: raycast

  #  - name: rectangle
  #    tags: rectangle

  #  - name: revolt
  #    tags: revolt

  #  - name: rhythmbox
  #    tags: rhythmbox

  #  - name: signal
  #    tags: signal

  #  - name: steam
  #    tags: steam

  #  - name: syncthing
  #    tags: syncthing

  #  - name: thunderbird
  #    tags: thunderbird

  #  - name: super-productivity
  #    tags: super-productivity

  #  - name: ulauncher
  #    tags: ulauncher

  #  - name: vagrant
  #    tags: vagrant

  #  - name: vaultwarden
  #    tags: vaultwarden

  #  - name: vivaldi
  #    tags: vivaldi

  #  - name: pwsh
  #    tags: pwsh

  #  - name: vagrant
  #    tags: vagrant

  #  - name: vlc
  #    tags: vlc

    - name: starship
      tags: starship

  tasks:
    - include_tasks: roles/finishing_touches/tasks/main.yml
    - include_tasks: roles/finishing_touches/tasks/finalize_zshrc.yml
    - include_tasks: roles/finishing_touches/tasks/update_first_run_variable.yml
    - include_tasks: roles/finishing_touches/tasks/send_notification.yml