---
# .dotfiles/main.yml

- name: Dotfiles Configuration
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Internet Connection Check
      include_tasks: pre_tasks/tasks/check_connection.yml
      tags:
        - always

    - name: Pre-tasks
      include_tasks: pre_tasks/tasks/main.yml
      tags:
        - pre_tasks

  # Software to install, uncomment any you wish to skip
  roles:
    - role: system
      tags: system

    - role: zsh
      tags: zsh

    - role: aerospace
      when: ansible_os_family == "Darwin"
      tags: aerospace

    - role: ssh
      tags: ssh

    - role: git
      tags: git

    - role: alacritty
      tags: alacritty

    - role: asciiquarium
      tags: asciiquarium

    - role: neofetch
      tags: neofetch

    - role: bat
      tags: bat

    - role: tmux
      tags: tmux

    - role: python
      tags: python

  #  - role: terraform
  #    tags: terraform

  #  - role: opentofu
  #    tags: opentofu

    - role: docker
      tags: docker

  #  - role: go
  #    tags: go

  #  - role: php
  #    tags: php

  #  - role: composer
  #    tags: composer

  #  - role: packer
  #    tags: packer

    - role: audacity
      tags: audacity

    - role: mailspring
      tags: mailspring

  #  - role: chromium
  #    tags: chromium

  #  - role: discord
  #    tags: discord

  #  - role: foliate
  #    tags: foliate

  #  - role: fusion360
  #    tags: fusion360

  #  - role: gimp
  #    tags: gimp

  #  - role: libreoffice
  #    tags: libreoffice

  #  - role: lutris
  #    tags: lutris

    - role: raycast
      tags: raycast

  #  - role: rectangle
  #    tags: rectangle

  #  - role: revolt
  #    tags: revolt

  #  - role: rhythmbox
  #    tags: rhythmbox

  #  - role: signal
  #    tags: signal

  #  - role: steam
  #    tags: steam

  #  - role: syncthing
  #    tags: syncthing

  #  - role: super-productivity
  #    tags: super-productivity

  #  - role: ulauncher
  #    tags: ulauncher

  #  - role: vagrant
  #    tags: vagrant

  #  - role: vaultwarden
  #    tags: vaultwarden

  #  - role: vivaldi
  #    tags: vivaldi

  #  - role: pwsh
  #    tags: pwsh

  #  - role: vagrant
  #    tags: vagrant

  #  - role: vlc
  #    tags: vlc

    - role: starship
      tags: starship
  
  post_tasks:
    - name: Set success
      set_fact:
        send_success: true

    - include_tasks: roles/finishing_touches/tasks/main.yml
    - include_tasks: roles/finishing_touches/tasks/finalize_zshrc.yml
    - include_tasks: roles/finishing_touches/tasks/update_first_run_variable.yml
    - include_tasks: roles/notifications/tasks/main.yml