---
- name: Dotfiles Configuration
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Internet Connection Check
      include_tasks: pre_tasks/check_connection.yml
      tags:
        - always

    - name: OS-specific pre-tasks
      include_tasks: pre_tasks/{{ ansible_os_family | lower }}.yml
      tags:
        - always

