---
# .dotfiles/main.yml

- name: Dotfiles Configuration
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Pre-tasks | Set OS identifier
      set_fact:
        system_os: "{{ 'macos' if ansible_os_family == 'Darwin' else ansible_os_family | lower }}"
      tags:
        - always

    - name: Pre-tasks | Internet Connection Check
      include_tasks: pre_tasks/check_connection.yml
      tags:
        - always
    
    - name: Pre-tasks | MacOS specific
      include_tasks: pre_tasks/macos.yml
      when: ansible_os_family == "Darwin"
      tags:
        - pre_tasks
    
    - name: Pre-tasks | Linux specific
      import_tasks: pre_tasks/debian.yml
      become: true
      when: ansible_os_family == "Debian"
      tags:
        - pre_tasks

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles with conditional privilege escalation
      include_role:
        name: "{{ roles_item }}"
      loop: "{{ run_roles }}"
      loop_control:
        loop_var: roles_item
      tags:
        - always