---
# .dotfiles/main.yml

- name: Dotfiles Configuration
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Set OS identifier
      set_fact:
        system_os: "{{ 'macos' if ansible_os_family == 'Darwin' else ansible_os_family | lower }}"
      tags:
        - always

    - name: Internet Connection Check
      include_tasks: pre_tasks/check_connection.yml
      tags:
        - always

    - name: OS-specific pre-tasks
      include_tasks: pre_tasks/{{ system_os | lower }}.yml
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles with conditional privilege escalation
      include_role:
        name: "{{ roles_item }}"
      loop: "{{ run_roles }}"
      loop_control:
        loop_var: roles_item
      tags:
        - always