---
- name: Dotfiles Configuration
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Internet Connection Check
      include_tasks: pre_tasks/check_connection.yml
      tags:
        - always

    - name: OS-specific pre-tasks
      include_tasks: pre_tasks/{{ ansible_os_family | lower }}.yml
      tags:
        - always

    - name: SSH
      include_tasks: roles/ssh/tasks/main.yml
      tags: 
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) | sort }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always