---
# .dotfiles/main.yml

- name: Dotfiles Configuration
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - group_vars/all.yml

  pre_tasks:
    - name: Pre-tasks | Internet Connection Check
      include_tasks: pre_tasks/check_connection.yml
      tags:
        - always
    
    - name: Pre-tasks | MacOS specific
      include_tasks: pre_tasks/macos.yml
      when: ansible_system == "Darwin"
      tags:
        - pre_tasks
    
    - name: Pre-tasks | Linux specific
      include_tasks: pre_tasks/linux.yml
      when: ansible_system == "Linux"
      tags:
        - pre_tasks

  # Software to install, uncomment any you wish to skip
  roles:
    - system
    - ssh
    - git
  #  - alacritty
    - asciiquarium
  #  - bat
  #  - starship
  #  - tmux
  #  - zsh
  #  - terraform
  #  - opentofu
  #  - ansible
  #  - docker
  #  - python
  #  - go
  #  - php
  #  - packer
  #  - audacity
  #  - autofs
  #  - betterbird
  #  - chromium
  #  - discord
  #  - foliate
  #  - fusion360
  #  - gimp
  #  - libreoffice
  #  - lutris
  #  - raycast
  #  - rectangle
  #  - revolt
  #  - rhythmbox
  #  - signal
  #  - steam
  #  - syncthing
  #  - thunderbird
  #  - super-productivity
  #  - ulauncher
  #  - vagrant
  #  - vaultwarden
  #  - vivaldi
  #  - pwsh
  #  - vlc

  tasks:

    # Source, just in case of changes
    - name: Finalizing | Setting source
      shell: source ~/.zshrc
      args:
        executable: /bin/zsh
      when: ansible_os_family in ["Darwin", "Debian", "Ubuntu", "Pop!_OS", "LinuxMint", "Kali", "Parrot"]
      tags:
        - always