---
# .dotfiles/requirements.yml

collections:
  - name: community.general
  - name: ansible.windows
  - name: community.windows
  - name: chocolatey.chocolatey
  - name: community.hashi_vault
  - name: community.docker
  - name: kubernetes.core