---
# .dotfiles/requirements.yml

roles:
  - name: townk.beautiful_output

collections:
  - name: community.general
  - name: ansible.windows
  - name: community.windows
  - name: chocolatey.chocolatey
#  - name: community.hashi_vault
  - name: community.docker
  - name: community.podman
  - name: kubernetes.core