---
# roles/notifications/tasks/gotify.yml

- name: Send success notification
  uri: 
    url: "https://{{ gotify_host }}/message?token={{ gotify_token }}"
    method: POST
    body_format: json
    body: 
      title: "Computer Setup Complete!"
      message: "Your computer has finished setting up."
      priority: 3
  # no_log: true
  when: send_success | default(false)
  tags:
    - gotify