---
# roles/wallpaper/tasks/debian.yml

- name: Wallpaper | {{ ansible_distrobution }} | Setup and configuration
  block:
    - name: Wallpaper | {{ ansible_distrobution }} | Ensure the Wallpaper directory exists
      file:
        path: "{{ wallpaper_directory_path }}"
        state: directory

    - name: Wallpaper | {{ ansible_distrobution }} | Copy wallpapers to the local directory
      copy:
        src: "{{ item.image }}"
        dest: "{{ wallpaper_directory_path }}/{{ item.image }}"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
      loop: "{{ wallpaper.virtual_desktop_wallpaper.values() | list | unique }}"
      loop_control:
        label: "{{ item.image }}"

  become: true
  tags:
    - wallpaper