---
# roles/wallpaper/tasks/gnome.yml

- name: Wallpaper | Ensure the Wallpaper directory exists
  file:
    path: "{{ wallpaper_directory_path }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  tags:
    - wallpaper

- name: Wallpaper | Copy main wallpaper to the local directory
  copy:
    src: "{{ wallpaper.main_wallpaper.image }}"
    dest: "{{ wallpaper_directory_path }}/{{ wallpaper.main_wallpaper.image }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  tags:
    - wallpaper

- name: Wallpaper | Set main wallpaper in GNOME
  shell: |
    gsettings set org.gnome.desktop.background picture-uri "file://{{ wallpaper_directory_path }}/{{ wallpaper.main_wallpaper.image }}"
  tags:
    - wallpaper