---
# roles/wallpaper/tasks/i3wm.yml

- name: Ensure required packages are installed
  apt:
    name:
      - feh
      - python3-i3ipc
    state: present
  become: true
  tags:
    - wallpaper

- name: Ensure i3 config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/i3"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags:
    - wallpaper

- name: Copy wallpapers to the local directory
  copy:
    src: "{{ item.image }}"
    dest: "{{ wallpaper_directory_path }}/{{ item.image }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ wallpaper.virtual_desktop_wallpaper.values() | list | unique }}"
  loop_control:
    label: "{{ item.image }}"
  tags:
    - wallpaper

- name: Create the wallpaper change script
  template:
    src: change_wallpaper.py.j2
    dest: "{{ ansible_env.HOME }}/.config/i3/change_wallpaper.py"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  tags:
    - wallpaper

- name: Ensure i3 config file exists
  file:
    path: "{{ ansible_env.HOME }}/.config/i3/config"
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags:
    - wallpaper

- name: Update i3 config to run the wallpaper change script
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/i3/config"
    line: 'exec --no-startup-id "{{ ansible_env.HOME }}/.config/i3/change_wallpaper.py"'
    insertafter: '^# Autostart applications'
    state: present
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags:
    - wallpaper

- name: Reload i3 configuration
  shell: i3-msg reload
  tags:
    - wallpaper