---
# roles/wallpaper/tasks/i3wm.yml

- name: Wallpaper | Ensure required packages are installed
  apt:
    name:
      - feh
      - python3-i3ipc
    state: present
  become: true
  tags:
    - wallpaper

- name: Wallpaper | Ensure i3 config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/i3"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  tags:
    - wallpaper

- name: Wallpaper | Copy wallpapers to the local directory
  copy:
    src: "{{ item.image }}"
    dest: "{{ wallpaper_directory_path }}/{{ item.image }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  loop: "{{ wallpaper.virtual_desktop_wallpaper.values() | list | unique }}"
  loop_control:
    label: "{{ item.image }}"
  tags:
    - wallpaper

- name: Wallpaper | Create the wallpaper change script
  template:
    src: change_wallpaper.py.j2
    dest: "{{ ansible_env.HOME }}/.config/i3/change_wallpaper.py"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  tags:
    - wallpaper

- name: Wallpaper | Ensure i3 config file exists
  file:
    path: "{{ ansible_env.HOME }}/.config/i3/config"
    state: touch
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
  tags:
    - wallpaper

- name: Wallpaper | Update i3 config to run the wallpaper change script
  lineinfile:
    path: "{{ ansible_env.HOME }}/.config/i3/config"
    line: 'exec --no-startup-id "{{ ansible_env.HOME }}/.config/i3/change_wallpaper.py"'
    insertafter: '^# Autostart applications'
    state: present
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
  tags:
    - wallpaper

- name: Wallpaper | Reload i3 configuration
  shell: i3-msg reload
  tags:
    - wallpaper