---
# roles/wallpaper/tasks/kde.yml

- name: Ensure the Wallpaper directory exists
  file:
    path: "{{ wallpaper_directory_path }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags:
    - wallpaper

- name: Copy main wallpaper to the local directory
  copy:
    src: "{{ wallpaper.main_wallpaper.image }}"
    dest: "{{ wallpaper_directory_path }}/{{ wallpaper.main_wallpaper.image }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags:
    - wallpaper

- name: Set main wallpaper in KDE Plasma
  shell: |
    qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript '
    var Desktops = desktops();
    for (i=0;i<Desktops.length;i++) {
      d = Desktops[i];
      d.wallpaperPlugin = "org.kde.image";
      d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");
      d.writeConfig("Image", "file://{{ wallpaper_directory_path }}/{{ wallpaper.main_wallpaper.image }}");
    }'
  tags:
    - wallpaper