---
# roles/wallpaper/tasks/macos.yml

- name: Ensure the Wallpaper directory exists
  file:
    path: "{{ wallpaper_directory_path }}"
    state: directory
    mode: '0755'
  tags:
    - wallpaper

- name: Copy all wallpaper files to local directory
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/Pictures/Wallpapers/"
    owner: "{{ ansible_env.USER }}"
    mode: '0644'
  with_fileglob:
    - "*"
  tags:
    - wallpaper

- name: Create AppleScript to set wallpapers
  template:
    src: set_wallpaper.applescript.j2
    dest: "{{ ansible_env.HOME }}/set_wallpaper.applescript"
  when: wallpaper.virtual_desktop_wallpaper is defined
  tags:
    - wallpaper

- name: Execute the AppleScript to set wallpapers
  shell: osascript "{{ ansible_env.HOME }}/set_wallpaper.applescript"
  when: wallpaper.virtual_desktop_wallpaper is defined
  tags:
    - wallpaper

- name: Remove the AppleScript
  file:
    path: "{{ ansible_env.HOME }}/set_wallpaper.applescript"
    state: absent
  when: wallpaper.virtual_desktop_wallpaper is defined
  tags:
    - wallpaper