---
# roles/wallpaper/tasks/main.yml

- name: Set wallpapers on macOS
  include_tasks: macos.yml
  when: ansible_os_family == 'Darwin'

- name: Set wallpapers on Linux
  include_tasks: linux.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat' or ansible_os_family == 'Archlinux'