---
# roles/wallpaper/tasks/main.yml

- name: MacOSX | Load install playbook
  include_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- name: Debian | Load install playbook
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"