---
- name: Asciiquarium | Detect any installed versions
  command:
    cmd: which asciiquarium
  changed_when: false
  failed_when: false
  register: is_installed

- name: Asciiquarium | Register any installed versions
  set_fact:
    is_installed: "{{ is_installed.stdout|default('') }}"

- name: Asciiquarium | Installed versions
  debug:
    var: is_installed

- name: Install
  block:
    - name: Asciiquarium | Install Dependencies
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - make
        - cpanminus
      become: true

    - name: Asciiquarium | Ensure clean location to download tarball
      file:
        path: /tmp/asciiquarium.tar.gz
        state: absent

    - name: Asciiquarium | Download the asciiquarium tarball"
      get_url:
        url: https://robobunny.com/projects/asciiquarium/asciiquarium.tar.gz
        dest: /tmp/asciiquarium.tar.gz
      notify:
        - Remove tarball

    - name: Asciiquarium | Extract the tarball
      unarchive:
        src: /tmp/asciiquarium.tar.gz
        dest: /tmp/

    - name: Asciiquarium | Install libcurses-perl
      apt:
        name: libcurses-perl
        state: present
      become: true

    - name: Asciiquarium | Install Term::Animation from CPAN
      cpanm:
        name: Term::Animation
      become: true

    - name: Asciiquarium | Install
      copy:
        remote_src: true
        src: /tmp/asciiquarium_1.1/asciiquarium
        dest: /usr/local/bin/
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        force: true
        mode: 0755
      become: true
      notify:
        - Remove extracted tarball

    - name: Asciiquarium | Add aliases to .zshrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: |
          # Asciiquarium
          alias brb=asciiquarium
          alias aq=asciiquarium

  when: is_installed | length < 1
  tags:
    - asciiquarium