---
# roles/asciiquarium/tasks/debian.yml

- name: Setup Asciiquarium
  block:

    - name: Install prerequisites
      apt:
        name:
          - software-properties-common
          - wget
          - gnupg
        state: present
        update_cache: yes

    - name: Create directory for APT keyrings
      file:
        path: "/etc/apt/keyrings"
        state: directory
        mode: 0755

    - name: Add Asciiquarium PPA GPG key to keyrings
      ansible.builtin.get_url:
        url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1A1B22F99CFDA64BD3B8D551F3985DE9980B9063"
        dest: "/etc/apt/keyrings/asciiquarium.gpg"
        mode: 0644

    - name: Add Asciiquarium APT repository with signed-by
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/asciiquarium.gpg] ppa:ytvwld/asciiquarium jammy main"
        state: present
        filename: "asciiquarium"

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install asciiquarium
      apt:
        name: asciiquarium
        state: present
        update_cache: yes

    - name: Add aliases to .zshrc
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: |
          # Asciiquarium
          alias brb=asciiquarium
          alias aq=asciiquarium

  become: true
  when: ansible_os_family == "Debian"
  tags:
    - asciiquarium