---
# roles/asciiquarium/tasks/macos.yml

- name: Setup Asciiquarium
  block:

    - name: Add repository
      apt_repository:
        repo: ppa:ytvwld/asciiquarium
        state: present

    - name: Update cache
      apt:
        update_cache: yes

    - name: Install asciiquarium
      apt:
        name: asciiquarium
        state: present
        update_cache: yes

    - name: Add aliases
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: |
          # Asciiquarium
          alias brb=asciiquarium
          alias aq=asciiquarium

  become: true
  when: ansible_os_family == "Debian"
  tags:
    - asciiquarium