---
# roles/asciiquarium/tasks/main.yml

- name: MacOSX | Install asciiquarium
  homebrew:
    name: asciiquarium
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - asciiquarium

- name: Debian-based | Install asciiquarium
  apt:
    name: asciiquarium
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - asciiquarium

- name: Add aliases
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      # Asciiquarium
      alias brb=asciiquarium
      alias aq=asciiquarium
  tags:
    - asciiquarium