---
# roles/asciiquarium/tasks/main.yml

- name: MacOSX | Install asciiquarium
  homebrew:
    name: asciiquarium
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - asciiquarium

- name: Debian-based | Install asciiquarium
  apt:
    name: asciiquarium
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - asciiquarium

- name: Check if aliases exist
  shell: grep -q '^# Asciiquarium' "{{ ansible_env.HOME }}/.zshrc"
  ignore_errors: true
  register: aq_aliases

- name: Add aliases with blank line before the block
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      # Asciiquarium
      alias brb=asciiquarium
      alias aq=asciiquarium
    state: present
    insertafter: EOF
    insertbefore: '^$'
  when: aq_aliases.rc != 0 
  tags:
    - asciiquarium