---
# roles/vscode/tasks/debian.yml

- name: VS Code | Setup and configure
  block:

    - name: VS Code | Download .deb package
      get_url:
        url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
        dest: "/tmp/vscode.deb"
        mode: '0644'

    - name: VS Code | Install VS Code via Apt
      apt:
        deb: "/tmp/vscode.deb"
        state: present
        update_cache: yes

    - name: VS Code | Remove .deb package
      file:
        path: "/tmp/vscode.deb"
        state: absent

  become: true
  tags:
    - vscode