---
# roles/mailspring/tasks/debian.yml

- name: Mailspring | Install via Apt
  block:
    - name: Mailspring | Downlaod mailspring .deb package
      get_url:
        url: "https://updates.getmailspring.com/download?platform=linuxDeb"
        dest: "/tmp/mailspring.deb"
        mode: 0644

    - name: Mailspring | Install mailspring
      apt:
        deb: "/tmp/mailspring.deb"
        update_cache: yes

    - name: Mailspring | Remove .deb package
      file:
        path: "/tmp/mailspring.deb"
        state: absent
  
  become: true
  tags:
    - mailspring