---
# roles/steam/tasks/macos.yml

- name: Check if Steam is already installed
  stat:
    path: "/Applications/Steam.app"
  register: steam_installed
  tags:
    - steam

- name: Install steam
  block:
    - name: Install steam
      homebrew_cask:
        name: steam
        state: present
    
    - name: Add to dock
      set_fact:
        dockitems_persist: "{{ dockitems_persist + [ { 'name': 'Steam', 'path': '/Applications/Steam.app', 'pos': '11' } ] }}"

  when: not steam_installed.stat.exists
  tags:
    - steam