---
# roles/steam/tasks/macos.yml

- name: Steam | Check if already installed
  stat:
    path: "/Applications/Steam.app"
  register: steam_installed
  tags:
    - steam

- name: Steam | Install via Homebrew
  homebrew_cask:
    name: steam
    state: present
  when: not steam_installed
  tags:
    - steam

- name: Steam | Add to dock
  set_fact:
    dockitems_persist: "{{ dockitems_persist + [ { 'name': 'Steam', 'path': '/Applications/Steam.app', 'pos': '11' } ] }}"
  tags:
    - steam