---
# roles/python/tasks/debian.yml

- name: Python | Install via Apt
  block:
    - name: Python | Install python packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - python3-setuptools
          - virtualenv
        state: present
        update_cache: true

    - name: Python | Ensure python interpreter is set to python 3
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

  become: true
  tags:
    - python