---
# roles/python/tasks/debian.yml

- name: Install python packages
  apt:
    name:
      - python3-venv
      - virtualenv
    state: present
  tags:
    - python

- name: Ensure python interpreter is set to python 3
  set_fact:
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - python