---
# roles/python/tasks/debian.yml

- name: Setup Python
  block:

    - name: Install python packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv 
          - virtualenv
        state: present

    - name: Ensure python interpreter is set to python 3
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

  become: true
  tags:
    - python