---
# roles/betterbird/tasks/macos.yml

- name: Download arm64 version
  set_fact: 
    betterbird_download_url: https://www.betterbird.eu/downloads/get.php?os=mac-arm64&lang=en-US&version=release
  when: ansible_facts['ansible_machine'] == 'arm64'
  tags:
    - betterbird

- name: Download x86 version
  set_fact: 
    betterbird_download_url: https://www.betterbird.eu/downloads/get.php?os=mac&lang=en-US&version=release
  when: ansible_facts['ansible_machine'] == 'x86_64'
  tags:
    - betterbird

- name: Download betterbird DMG
  get_url:
    url: "{{ betterbird_download_url }}"
    dest: "/tmp/Betterbird.dmg"
    mode: 0644
  tags:
    - betterbird

- name: Mount the DMG file
  shell: |
    hdiutil attach -nobrowse -quiet /tmp/Betterbird.dmg
  register: hdiutil_attach
  changed_when: "'already mounted' not in hdiutil_attach.stderr"
  tags:
    - betterbird

- name: Get the mount point
  shell: |
    echo "{{ hdiutil_attach.stdout | regex_search('(/Volumes/Betterbird[^\n]*)') }}"
  register: mount_point
  chagned_when: false
  tags:
    - betterbird

- name: Copy Betterbird.app to /Applications
  copy:
    src: "{{ mount_point.stdout }}/Betterbird.app"
    dest: "/Applications/Betterbird.app"
  remote_src: yes
  tags:
    - betterbird

- name: Unmount the DMG file
  shell: |
    hdiutil detach -quiet "{{ mount_point.stdout }}"
  ignore_errors: true
  tags:
    - betterbird

- name: Remove the DMG file
  file:
    path: "/tmp/Betterbird.dmg"
    state: absent
  tags:
    - betterbird