---
# roles/aerospace/tasks/macos.yml

- name: Add Homebrew tap for Aerospace
  homebrew_tap:
    name: nikitabobko/tap
    state: present
  tags:
    - aerospace

- name: Install Aerospace
  homebrew_cask:
    name: aerospace
    state: present
  tags:
    - aerospace