---
# roles/aerospace/tasks/macos.yml

- name: Aerospace | Add Homebrew tap
  homebrew_tap:
    name: nikitabobko/tap
    state: present
  tags:
    - aerospace

- name: Aerospace | Install
  homebrew_cask:
    name: aerospace
    state: present
  tags:
    - aerospace