---
# roles/aliases/tasks/debian.yml

- name: Aliases | Render .aliases file
  template:
    src: aliases.j2
    dest: "{{ ansible_facts.env.HOME }}/.aliases"
    owner: "{{ ansible_facts.env.USER }}"
    group: "{{ ansible_facts.env.USER }}"
    mode: '0644'
  tags:
    - aliases

- name: Aliases | Source .aliases from .zshrc
  lineinfile:
    path: "{{ ansible_facts.env.HOME }}/.zshrc"
    line: |
      # Load aliases
      source ~/.aliases
    insertafter: EOF
  tags:
    - aliases
