---
# roles/aliases/tasks/macos.yml

- name: Aliases | Copy .aliases file
  copy:
    src: aliases
    dest: "{{ ansible_facts.env.HOME }}/.aliases"
    owner: "{{ ansible_facts.env.USER }}"
    group: "staff"
    mode: 0644
  tags:
    - aliases

- name: Aliases | Source .aliases from .zshrc
  lineinfile:
    path: "{{ ansible_facts.env.HOME }}/.zshrc"
    line: |
      # Load aliases
      source ~/.aliases
    insertafter: EOF
  tags:
    - aliases
