---
# roles/ssh/tasks/ssh.yml

- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700
  tags:
    - ssh

- name: Copy SSH keys
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "{{ ssh_key_item.key.endswith('.pub') | ternary('0644', '0600') }}"
  no_log: true
  loop: "{{ ssh_keys | default({}) | dict2items }}"
  loop_control:
    label: "{{ ssh_key_item.key }}"
    loop_var: ssh_key_item
  tags:
    - ssh

- name: Copy SSH config
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    content: "{{ ssh_configs }}"
    mode: 0644
  tags:
    - ssh

- name: Copy SSH known_host
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    content: "{{ ssh_known_hosts }}"
    mode: 0644
  tags:
    - ssh

- name: Add aliases
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      # SSH aliases
      alias ssha='eval $(ssh-agent) && ssh-add'
  tags:
    - ssh