---
# roles/system/tasks/debian.yml

# Add HashiCorp GPG key for Vagrant
- name: System | Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true
  tags:
    - system

# Add Btop GPG key (if using the PPA)
- name: System | Add Btop GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 91A6E7F0
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
    - system

# Add Zoxide GPG key (if using the PPA)
- name: System | Add Zoxide GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: A0B04B9F10496B85
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
    - system

- name: System | Update cache
  apt:
    update_cache: true
  become: true
  tags:
    - system

# Install system packages via Apt
- name: System | Install system packages (debian-based)
  apt:
    name:
      - build-essential
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - sudo
      - wget
      - git
      - zsh
      - sshfs
      - net-tools
      - nmap
      - htop
      - btop
      - unzip
      - traceroute
      - dnsutils
      - iftop
      - cron
      - logrotate
      - netstat
      - zoxide
      - rsync
      - locales
      - language-pack-en
      - language-pack-jp
      - rar
      - unrar
      - xz-utils
      - ffmpeg
      - qemu-kvm
      - vagrant
    state: present
  become: true
  tags:
    - system

# ZSH tasks
- name: System | ZSH
  block:
    - name: "System | ZSH | Set default terminal"
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        shell: /usr/bin/zsh
      become: true

    - name: System | ZSH | Check if .zshrc exists
      stat:
        path: "{{ ansible_env.HOME }}/.zshrc"
      register: zshrc_exists
    
    - name: System | ZSH | Create or update .zshrc configuration
      copy:
        dest: "{{ ansible_env.HOME }}/.zshrc"
        content: |
          # {{ ansible_managed }}

          # Set system PATH just in case
          export PATH="/usr/local/bin:$PATH"

          # Convienece aliases
          alias update='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y'

          # History setup
          HISTFILE=$HOME/.zhistory
          SAVEHIST=1000
          HISTSIZE=999
          setopt share_history
          setopt hist_expire_dups_first
          setopt hist_ignore_dups
          setopt hist_verify
          bindkey "^[[A" history-search-backward # Up arrow
          bindkey "^[[B" history-search-forward # Down arrow
        mode: 0600
      when: zshrc_exists.stat.exists == false
  tags:
    - system