---
# roles/system/tasks/debian.yml

## Add HashiCorp GPG key for Vagrant
#- name: Add HashiCorp GPG key
#  apt_key:
#    url: https://apt.releases.hashicorp.com/gpg
#    state: present
#  become: true
#  tags:
#    - system
#
## Add Btop GPG key (if using the PPA)
#- name: Add Btop GPG key
#  apt_key:
#    keyserver: keyserver.ubuntu.com
#    id: 91A6E7F0
#    state: present
#  become: true
#  when: ansible_distribution == "Ubuntu"
#  tags:
#    - system
#
## Add Zoxide GPG key (if using the PPA)
#- name: Add Zoxide GPG key
#  apt_key:
#    keyserver: keyserver.ubuntu.com
#    id: A0B04B9F10496B85
#    state: present
#  become: true
#  when: ansible_distribution == "Ubuntu"
#  tags:
#    - system

- name: System | Update cache
  apt:
    update_cache: true
    upgrade: full
  become: true
  tags:
    - system

# Install system packages via Apt
- name: System | Install system packages
  apt:
    name:
      - build-essential
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https
      - software-properties-common
      - sudo
      - wget
      - git
      - sshfs
      - nmap
      - htop
      - unzip
      - traceroute
      - dnsutils
      - iftop
      - cron
      - logrotate
      - rsync
      - locales
      - rar
      - unrar
      - xz-utils
      - ffmpeg
      - qemu-kvm
      - i3
    state: present
  become: true
  tags:
    - system

- name: System | Ensure keyring directory exists
  file:
    path: "/usr/share/keyrings/"
    state: directory
  tags:
    - system

- name: System | Create .config directory
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
  tags:
    - system

- name: System | Create autostart directory
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart/"
    state: directory
  tags:
    - system