---
# roles/system/tasks/debian.yml

# Add HashiCorp GPG key for Vagrant
- name: System | Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true
  tags:
    - system

# Add Btop GPG key (if using the PPA)
- name: System | Add Btop GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 91A6E7F0
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
    - system

# Add Zoxide GPG key (if using the PPA)
- name: System | Add Zoxide GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: A0B04B9F10496B85
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"
  tags:
    - system

- name: System | Update cache
  apt:
    update_cache: true
  become: true
  tags:
    - system

# Install system packages via Apt
- name: System | Install system packages (debian-based)
  apt:
    name:
      - build-essential
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - sudo
      - wget
      - git
      - sshfs
      - net-tools
      - nmap
      - htop
      - btop
      - unzip
      - traceroute
      - dnsutils
      - iftop
      - cron
      - logrotate
      - netstat
      - zoxide
      - rsync
      - locales
      - language-pack-en
      - language-pack-jp
      - rar
      - unrar
      - xz-utils
      - ffmpeg
      - qemu-kvm
    state: present
  become: true
  tags:
    - system