---
# roles/system/tasks/macos.yml

- name: Install system packages
  homebrew:
    name:
      - autoconf
      - automake
      - wget
      - htop
      - btop
      - nmap
      - netcat
      - zoxide
      - ffmpeg
      - tree
      - jq
      - ripgrep
      - neofetch
      - gnupg
      - coreutils
      - findutils
      - git 
      - gnu-sed
      - gawk
      - watch
      - gnu-tar
    state: present
  tags:
    - system

- name: Tap the Homebrew tap
  homebrew_tap:
    name: nikitabobko/tap
    state: present
  tags:
    - brew

- name: Install Aerospace app via Homebrew Cask
  homebrew_cask:
    name: aerospace
    state: present
  tags:
    - brew