---
# roles/system/tasks/macos.yml

# Install system packages via Homebrew
- name: System | Install system packages
  homebrew:
    name:
      - autoconf
      - automake
      - wget
      - htop
      - btop
      - nmap
      - netcat
      - zoxide
      - ffmpeg
      - tree
      - jq
      - ripgrep
      - neofetch
      - gnupg
      - coreutils
      - findutils
      - git 
      - gnu-sed
      - gawk
      - watch
      - gnu-tar
    state: present
  tags:
    - system