---
# roles/zsh/tasks/debian.yml

- name: ZSH | Setup and configure
  block:
    - name: ZSH | Install via Apt
      apt:
        name: zsh
        state: latest

    - name: ZSH | Set default shell to Zsh
      command: chsh -s "$(which zsh)" "{{ ansible_env.USER }}"

    - name: ZSH | Install syntax highlighting
      apt:
        name: zsh-syntax-highlighting
        state: latest

    - name: ZSH | Install auto-suggestions
      apt:
        name: zsh-autosuggestions
        state: latest

    - name: ZSH | Check if .zshrc exists already
      stat:
        path: "{{ ansible_env.HOME }}/.zshrc"
      register: zshrc_file

    - name: ZSH | Backup existing .zshrc if it exists
      copy:
        src: "{{ ansible_env.HOME }}/.zshrc"
        dest: "{{ ansible_env.HOME }}/.zshrc.bak"
        remote_src: yes
        backup: yes
      when: zshrc_file.stat.exists

    - name: ZSH | Create .zshrc from template
      template:
        src: zshrc.j2
        dest: "{{ ansible_env.HOME }}/.zshrc"
  
  become: true
  tags:
    - zsh