---
# roles/zsh/tasks/debian.yml

- name: Install Zsh
  apt:
    name: zsh
    state: present
  become: true
  tags:
    - zsh

- name: "Set default terminal"
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  become: true
  tags:
    - zsh

- name: Install syntax highlighting
  apt:
    name: zsh-syntax-highlighting
    state: present
  tags:
    - zsh

- name: Install auto-suggestions
  apt:
    name: zsh-autosuggestions
    state: present
  tags:
    - zsh