---
# roles/zsh/tasks/macos.yml

- name: Install syntax highlighting
  homebrew:
    name: zsh-syntax-highlighting
    state: present
  tags:
    - zsh

- name: Install auto-suggestions
  homebrew:
    name: zsh-autosuggestions
    state: present
  tags:
    - zsh