general.live_config_reload = true

general.import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 1
dynamic_padding = false
decorations = "buttonless"
position = { x = 0, y = 0 }
startup_mode = "SimpleFullscreen"

option_as_alt = "Both"

[font]
size = 16
offset.x = 1
offset.y = 1

normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

[cursor.style]
shape = "Block"
blinking = "Always"

[selection]
save_to_clipboard = true

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  { key = "L",        mods = "Control",       chars  = "\f" },
  { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]