# General Configuration
"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# ╭─(white)$username$hostname in \
# $directory\
# $git_branch$git_status\
# $fill\
# $python\
# $php\
# $nodejs\
# $golang\
# $rust\
# $zig\
# $package\
# $aws\
# $docker_context\
# $jobs\
# $cmd_duration\
# $line_break\
# ╰─$character"""

# GLOBAL FORMAT
format = """
$username\
$hostname \
$localip\
$shlvl\
$kubernetes\
${custom.giturl}\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
${custom.docker}\
$package\
$c\
$deno\
$dotnet\
$golang\
$zig\
$guix_shell\
$helm\
$java\
$lua\
$nim\
$nodejs\
$perl\
$php\
$purescript\
$python\
$rust\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$directory\
$character"""

# Add line between commands
add_newline = true

# Color palette to use
palette = 'catppuccin_macchiato'

# Palette Definitions
[palettes.dracula]
dark_blue = '#6272a4'
blue = '#8be9fd'
teal = '#8be9fd'
red = '#ff5555'
orange = '#ffb86c'
green = '#50fa7b'
yellow = '#f1fa8c'
purple = '#bd93f9'
gray = '#44475a'
black = '#282a36'
white = '#f8f8f2'

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Fill Module
[fill]
symbol = ' '

# Character Module
[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'
vimcmd_symbol = '[❯](bold green)'
vimcmd_replace_one_symbol = '[❯](bold purple)'
vimcmd_replace_symbol = '[❯](bold purple)'
vimcmd_visual_symbol = '[❯](bold yellow)'

# Username settings
[username]
show_always = true
style_root = "bold red"
style_user = "bold yellow"
format = "[$user]($style) "
disabled = false

# Hostname Module
[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow)'
trim_at = "."
disabled = false
ssh_symbol = " "

# Time Module
#[time]
#disabled = false
#time_format = "%R"
#style = "bold fg:purple"
# Removed the 'symbol' key and incorporated the symbol directly into the format string
#format = '[  $time ](fg:purple bg:black)'

# Directory Module
[directory]
style = 'bold fg:teal'
# format = '[$path ]($style)'
format = "[$read_only]($read_only_style)[$path]($style) "
truncation_length = 8 # 3
truncation_symbol = '…/'
truncate_to_repo = false
read_only = " 󰌾"
read_only_style = "red"

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

# Jobs Module
[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

# Command Duration Module
[cmd_duration]
min_time = 100
style = 'fg:yellow'
format = '[ $duration]($style)'

# Git Branch Module
[git_branch]
style = 'fg:green'
symbol = " "
format = '[on](white) [$symbol$branch ]($style)'

# Git Status Module
[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

# Python Module
[python]
style = 'teal'
symbol = " "
format = '[${symbol}${version} (\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

# AWS Module
[aws]
symbol = "  "
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

# Docker Context Module
[docker_context]
symbol = " Docker"
style = 'fg:teal'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

# OS Module
[os]
disabled = false
style = "fg:purple"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

# Additional Modules with Symbols
[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "