# General Configuration
"$schema" = 'https://starship.rs/config-schema.json'

format = """
╭─(white)$username$hostname in \
$directory\
$git_branch$git_status\
$fill\
$python\
$php\
$nodejs\
$golang\
$rust\
$zig\
$package\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
╰─$character"""

# Add line between commands
add_newline = true

# Color palette to use
palette = 'dracula'

# Palette Definitions
[palettes.dracula]
dark_blue = '#6272a4'
blue = '#8be9fd'
teal = '#8be9fd'
red = '#ff5555'
orange = '#ffb86c'
green = '#50fa7b'
yellow = '#f1fa8c'
purple = '#bd93f9'
gray = '#44475a'
black = '#282a36'
white = '#f8f8f2'

# Fill Module
[fill]
symbol = ' '

# Character Module
[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'
vimcmd_symbol = '[❯](bold green)'
vimcmd_replace_one_symbol = '[❯](bold purple)'
vimcmd_replace_symbol = '[❯](bold purple)'
vimcmd_visual_symbol = '[❯](bold yellow)'

# Username settings
[username]
show_always = true
style_root = "bold red"
style_user = "bold yellow"
format = "[$user]($style) "
disabled = false

# Hostname Module
[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow)'
trim_at = "."
disabled = false
ssh_symbol = " "

# Time Module
#[time]
#disabled = false
#time_format = "%R"
#style = "bold fg:purple"
# Removed the 'symbol' key and incorporated the symbol directly into the format string
#format = '[  $time ](fg:purple bg:black)'

# Directory Module
[directory]
style = 'bold fg:teal'
# format = '[$path ]($style)'
format = "[$read_only]($read_only_style)[$path]($style) "
truncation_length = 8 # 3
truncation_symbol = '…/'
truncate_to_repo = false
read_only = " 󰌾"
read_only_style = "red"

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

# Jobs Module
[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

# Command Duration Module
[cmd_duration]
min_time = 100
style = 'fg:yellow'
format = '[ $duration]($style)'

# Git Branch Module
[git_branch]
style = 'fg:green'
symbol = " "
format = '[on](white) [$symbol$branch ]($style)'

# Git Status Module
[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

# Python Module
[python]
style = 'teal'
symbol = " "
format = '[${symbol}${version} (\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

# AWS Module
[aws]
symbol = "  "
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

# Docker Context Module
[docker_context]
symbol = " Docker"
style = 'fg:teal'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

# OS Module
[os]
disabled = false
style = "fg:purple"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

# Additional Modules with Symbols
[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "