---
# roles/brave/tasks/debian.yml

- name: Brave | Setup and configuration
  block:
    - name: Brave | Add Brave APT repository key
      get_url:
        url: "https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
        dest: "/etc/apt/keyrings/brave-browser-archive-keyring.gpg"
        owner: root
        group: root
        validate_certs: yes
        mode: '0644'
        force: true

    - name: Brave | Add Brave APT repository
      apt_repository: 
        repo: "deb [signed-by=/etc/apt/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        filename: "brave-browser-release"
        state: present

    - name: Brave | Update APT cache
      apt:
        update_cache: yes

    - name: Brave | Install Brave browser
      apt:
        name: brave-browser
        state: present
  
  become: true
  tags:
    - brave