---
# roles/brave/tasks/debian.yml

- name: Check if Brave Browser is already installed
  stat:
    path: "/usr/bin/brave-browser"
  register: brave_installed
  tags:
    - brave_browser

- name: Install Brave
  block:
    - name: Add Brave GPG key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        state: present

    - name: Add Brave APT repository
      apt_repository: 
        repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        state: present
        filename: "brave-browser-release"

    - name: Update APT cache
      apt:
        update_cache: yes
    
    - name: Install Brave browser
      apt:
        name: brave-browser
        state: present

  when: not brave_installed.stat.exists
  become: true
  tags:
    - brave