---
# roles/brave/tasks/macos.yml

- name: Install brave browser
  homebrew_cask:
    name: brave
    state: present
  tags:
    - brave

- name: Add to dock
  set_fact:
    dockitems_persist: "{{ dockitems_persist + [ { 'name': 'Brave', 'path': '/Applications/Brave.app', 'pos': 6 } ] }}"