---
# roles/nordvpn/tasks/debian.yml

- name: NordVPN | Download and installation
  block:
    - name: NordVPN | Install python3-apt
      apt:
        name: python3-apt
        state: present
        force_apt_get: yes
        update_cache: true

    - name: NordVPN | Installing gnupg2
      apt:
        name: gnupg2
        state: present
        force_apt_get: yes
        update_cache: true

    - name: NordVPN | Add NordVPN's official GPG key
      get_url:
        url: "https://repo.nordvpn.com/gpg/nordvpn_public.asc"
        dest: /etc/apt/keyrings/nordvpn.gpg
        mode: '0644'
        owner: root
        group: root
        validate_certs: yes


    - name: NordVPN | Adding repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/nordvpn.gpg] https://repo.nordvpn.com//deb/nordvpn/debian stable main"
        filename: "nordvpn"
        state: present
        update_cache: yes

    - name: NordVPN | Installing Nord VPN
      apt:
        name: "nordvpn"
        state: present
        force_apt_get: yes
        update_cache: yes

    - name: NordVPN | Add user to group
      user:
        name: "{{ ansible_env.USER }}"
        groups: "nordvpn"
        append: yes
  
  become: true
  tags:
    - nordvpn