---
# roles/nordvpn/tasks/debian.yml

- name: Check if NordVPN is already installed
  stat:
    path: "/usr/bin/nordvpn"
  register: nordvpn_installed
  tags:
    - nordvpn

- name: Install NordVPN
  block:
    - name: Download NordVPN install script
      get_url:
        url: "https://downloads.nordcdn.com/apps/linux/install.sh"
        dest: "/tmp/install_nordvpn.sh"
        mode: 0755

    - name: Run NordVPN install script
      command: /bin/bash /tmp/install_nordvpn.sh
      args:
        creates: "/usr/bin/nordvpn"

    - name: Ensure the 'nordvpn' group exists
      group:
        name: nordvpn
        state: present

    - name: Add user to 'nordvpn' group
      user:
        name: "{{ ansible_user }}"
        groups: nordvpn
        append: yes

    - name: Remove NordVPN install script
      file:
        path: "/tmp/install_nordvpn.sh"
        state: absent

  when: not nordvpn_installed.stat.exists
  become: true
  tags:
    - nordvpn