---
# roles/nordvpn/tasks/debian.yml

- name: Check if NordVPN is already installed
  stat:
    path: "/usr/bin/nordvpn"
  register: nordvpn_installed
  tags:
    - nordvpn

- name: Install NordVPN
  block:
    - name: Install python3-apt
      ansible.builtin.apt:
        name: python3-apt
        state: present
        force_apt_get: yes
        update_cache: yes

    - name: Installing gnupg2
      ansible.builtin.apt:
        name: gnupg2
        state: present
        force_apt_get: yes

    - name: Add GPG signing key
      ansible.builtin.apt_key:
        url: "https://repo.nordvpn.com/gpg/nordvpn_public.asc"
        state: present

    - name: Adding repository
      ansible.builtin.apt_repository:
        repo: "deb https://repo.nordvpn.com//deb/nordvpn/debian stable main"
        filename: "nordvpn"
        state: present
        update_cache: yes

    - name: Installing Nord VPN
      ansible.builtin.apt:
        name: "nordvpn"
        state: present
        force_apt_get: yes
        update_cache: yes

    - name: Add user to group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env.USER }}"
        groups: "nordvpn"
        append: yes

  when: not nordvpn_installed.stat.exists
  become: true
  tags:
    - nordvpn