---
# roles/nordvpn/tasks/macos.yml

- name: Install Nord VPN
  block:
    - name: Install Nord VPN
      homebrew_cask:
        name: nordvpn
        state: present

    - name: Add to dock
      set_fact:
        dockitems_persist: "{{ dockitems_persist + [ { 'name': 'NordVPN', 'path': '/Applications/NordVPN.app', 'pos': 2 } ] }}"

  tags:
    - nordvpn