---
# roles/homebrew/tasks/main.yml

- name: Update and upgrade Homebrew
  community.general.homebrew:
      update_homebrew: true
      upgrade_all: true

# Enable passwordless sudo for homebrew
- name: "Enable passwordless sudo for homebrew"
  ansible.builtin.template:
    src: "user-sudo.j2"
    dest: /private/etc/sudoers.d/{{ ansible_env['USER'] }}
    mode: "0440"
  become: true
  tags:
    - homebrew