---
# roles/foliate/tasks/debian.yml

- name: Foliate | Install via Flatpack
  flatpak:
    name: com.github.johnfactotum.Foliate
    method: user
    state: present
  become: true
  tags:
    - foliate