---
# roles/chrome/tasks/macos.yml

- name: Chrome | Check if Chrome is already installed
  stat:
    path: "/Applications/Chrome.app"
  register: chrome_installed
  tags:
    - chrome

- name: Chrome | Setup and Configuration
  block:
    - name: Install Chrome
      homebrew_cask:
        name: google-chrome
        state: present
    
    - name: Add to dock
      set_fact:
        dockitems_persist: "{{ dockitems_persist + [ { 'name': 'Chrome', 'path': '/Applications/Chrome.app', 'pos:' '9' } ] }}"

  when: not chrome_installed.stat.exists
  tags:
    - chrome