---
# roles/discord/tasks/debian.yml

- name: Discord | Setup and configuration
  block:
    - name: Discord | Download .deb package
      get_url:
        url: "https://discord.com/api/download?platform=linux&format=deb"
        dest: "/tmp/discord.deb"
        mode: '0644'

    - name: Discord | Install discord
      apt:
        deb: "/tmp/discord.deb"
        update_cache: yes

    - name: Discord | Remove .deb package
      file:
        path: "/tmp/discord.deb"
        state: absent
  become: true
  tags:
    - discord