---
# roles/discord/tasks/macos.yml

- name: Discord | Check if Discord is already installed
  stat:
    path: "/Applications/Discord.app"
  register: discord_installed
  tags:
    - discord

- name: Discord | Setup and Configuration
  block:
    - name: Install Discord
      homebrew_cask:
        name: discord
        state: present

    - name: Add to dock
      set_fact:
        dockitems_persist: "{{ dockitems_persist + [ { 'name': 'Discord', 'path': '/Applications/Discord.app', 'pos:' '3' } ] }}"
  when: not discord_installed.stat.exists
  tags:
    - discord