---
# roles/tmux/tasks/debian.yml

- name: Setup Tmux
  block:

    - name: Install tmux
      apt:
        name: tmux
        state: present

    - name: Copy tmux configuration
      copy:
        src: tmux.conf
        dest: "{{ ansible_env.HOME }}/.config/tmux"
        mode: 0644
        directory_mode: 0755
        force: true

  become: true
  tags:
    - tmux