---
# roles/tmux/tasks/debian.yml

- name: Tmux | Setup and configure
  block:

    - name: Tmux | Install tmux via Apt
      apt:
        name: tmux
        state: present

    - name: Tmux | Copy tmux configuration
      copy:
        src: tmux.conf
        dest: "{{ ansible_env.HOME }}/.config/tmux"
        mode: '0644'
        directory_mode: '0755'
        force: true

  become: true
  tags:
    - tmux