---
# roles/tmux/tasks/debian.yml

- name: Install tmux
  apt:
    name: tmux
    state: present
  become: true
  tags:
    - tmux

- name: Copy tmux configuration
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.config/tmux"
    mode: 0644
    directory_mode: 0755
    force: true