---
# roles/tmux/tasks/macos.yml

- name: Install tmux
  homebrew:
    name: tmux
    state: present
  tags:
    - tmux

- name: Copy tmux configuration
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.config/tmux"
    mode: 0644
    directory_mode: 0755
    force: true