---
# roles/vivaldi/tasks/macos.yml

- name: Install vivaldi
  homebrew_cask:
    name: vivaldi
    state: present
  tags:
    - vivaldi

- name: Add to dock
  set_fact:
    dockitems_persist: "{{ dockitems_persist + [ { 'name': '/Applications/Vivaldi.app', 'pos': 7 } ] }}"
  tags:
    - vivaldi