---
# roles/finishing_touches/tasks/debian.yml

- name: Finishing Touches | Update Apt cache
  apt:
    update_cache: true
  when: ansible_os_family in ["Debian", "Ubuntu", "Pop!_OS", "LinuxMint", "Kali", "Parrot"]
  tags:
    - always

- name: Finishing Touches | Cleanup Apt
  apt:
    autoclean: true
  when: ansible_os_family in ["Debian", "Ubuntu", "Pop!_OS", "LinuxMint", "Kali", "Parrot"]
  tags: 
    - always

- name: Finishing Touches | Set source # Source, just in case of changes 
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  when: ansible_os_family in ["Debian", "Ubuntu", "Pop!_OS", "LinuxMint", "Kali", "Parrot"]
  tags:
    - always