---
# roles/finishing_touches/tasks/debian.yml

- name: Finishing Touches | Update Apt cache
  apt:
    update_cache: true
  become: true
  tags:
    - always

- name: Finishing Touches | Cleanup Apt
  apt:
    autoclean: true
  become: true
  tags: 
    - always

- name: Finishing Touches | Set source # Source, just in case of changes 
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  tags:
    - always

- name: Finishing Touches | Set default desktop environment to i3wm
  ini_file:
    path: "/var/lib/AccountsService/users/{{ ansible_user }}"
    section: "User"
    option: "XSession"
    value: "i3"
    create: yes
  notify: Restart AccountsService
  become: true
  tags:
    - always