---
# roles/finishing_touches/tasks/finalize_zshrc.yml

- name: Set Starship prompt in shell
  lineinfile:
    path: "{{ ansible_facts.env.HOME }}/.zshrc"
    line: |
      # Starship
      eval "$(starship init zsh)"
    insertafter: EOF
  become_user: "{{ ansible_facts.env.USER }}"
  tags:
    - always