---
# roles/finishing_touches/tasks/macos.yml

- name: Set source # Source, just in case of changes 
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  when: ansible_os_family == "Darwin"
  tags:
    - always

- name: Install dockutil.
  homebrew:
    name: dockutil
    state: present
  notify: 
    - update_homebrew
    - cleanup_homebrew
  tags: 
    - always

- name: Remove default dock items
  vars:
    dockitems_remove:
      - TV
      - Podcasts
      - Launchpad
      - 'App Store'
      - Safari
      - Mail
      - FaceTime
      - Maps
      - Photos
      - Contacts
      - Calendar
  include_tasks: macos_dock_remove.yml
  loop: "{{ dockitems_remove }}"
  loop_control:
    extended: true
    extended_allitems: false
  tags:
    - always

- name: Add wanted apps to dock
  block:
    - include_tasks: macos_dock_add.yml
      loop: "{{ dockitems_persist }}"
      loop_control:
        extended: true
        extended_allitems: false
    - include_tasks: macos_dock_persist.yml
      loop: "{{ dockitems_persist }}"
      loop_control:
        extended: true
        extended_allitems: false
  tags:
    - always