---
# roles/finishing_touches/tasks/macos.yml

- name: Update Homebrew cache
  homebrew:
    update_homebrew: true
    upgrade_all: true
  when: ansible_os_family == "Darwin"
  tags:
    - always

- name: Cleanup Homebrew
  shell: brew cleanup
  when: ansible_os_family == "Darwin"
  tags: 
    - always

- name: Set source # Source, just in case of changes 
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  when: ansible_os_family == "Darwin"
  tags:
    - always