---
# roles/finishing_touches/tasks/main.yml

- name: MacOSX | Load finishing touches
  include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  tags:
    - always

- name: Debian | Load finishing touches
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - always

- name: Finalize ZSHRC file
  include_tasks: finalize_zshrc.yml
  when: ansible_os_family in ("Darwin", "Debian")
  tags:
    - always

- name: Update first run variable
  include_tasks: update_first_run_variable.yml
  tags:
    - always