---
# roles/finishing_touches/tasks/main.yml

- name: MacOSX | Load finishing touches
  include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  tags:
    - always

- name: Debian | Load finishing touches
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - always