---
# roles/finishing_touches/tasks/update_first_run.yml

  # Change the first_play variable to false 
- name: Set first_play variable to false
  lineinfile:
    path: "{{ playbook_dir }}/group_vars/all.yml"
    regexp: '^first_play:'
    line: "first_play: false"
  when: first_play == true
  tags:
    - always