---
# roles/teleport/tasks/debian.yml

- name: Teleport | Check if Teleport is already installed
  stat:
    path: "/usr/bin/teleport"
  register: teleport_installed
  tags:
    - teleport

- name: Teleport | Setup and configure
  block:
    - name: Teleport | Download Teleport .deb package
      get_url:
        url: "https://desktop.wifiman.com/wifiman-desktop-1.1.0-amd64.deb"
        dest: "/tmp/wifiman.deb"
        mode: '0644'

    - name: Teleport | Install Teleport via Apt
      apt:
        deb: "/tmp/wifiman.deb"
        state: present

    - name: Teleport | Update apt cache
      apt: 
        update_cache: yes

    - name: Teleport | Remove Teleport .deb package for Intel (amd64)
      file:
        path: "/tmp/wifiman.deb"
        state: absent

  when: not teleport_installed.stat.exists
  become: true
  tags:
    - teleport