---
# roles/teleport/tasks/debian.yml

- name: Check if Teleport is already installed
  stat:
    path: "/usr/bin/teleport"
  register: teleport_installed
  tags:
    - teleport

- name: Install Teleport
  block:
    - name: Set Teleport package URL based on architecture
      set_fact:
        teleport_deb_url: >
          {% if ansible_architecture == 'x86_64' %}
            https://desktop.wifiman.com/wifiman-desktop-1.1.0-amd64.deb
          {% elif ansible_architecture == 'aarch64' %}
            https://desktop.wifiman.com/wifiman-desktop-1.1.0-arm64.deb
          {% else %}
            https://desktop.wifiman.com/wifiman-desktop-1.1.0-default.deb
          {% endif %}
  
    - name: Download Teleport .deb package
      get_url:
        url: "{{ teleport_deb_url }}"
        dest: "/tmp/wifiman-desktop.deb"
        mode: 0644

    - name: Install Teleport package
      dpkg:
        name: "/tmp/wifiman-desktop.deb"
        state: present

    - name: Update apt cache
      apt: 
        update_cache: yes

    - name: Verify Teleport installation
      stat:
        path: "/usr/bin/teleport"
      register: teleport_post_install

    - name: Remove Teleport .deb package for Intel (amd64)
      file:
        path: "/tmp/wifiman-desktop.deb"
        state: absent

  when: not teleport_installed.stat.exists
  become: true
  tags:
    - teleport