---
# roles/neofetch/tasks/debian.yml

- name: Neofetch | Install via Apt
  block:
    - name: Neofetch | Install
      apt:
        name: neofetch
        state: present
      tags:
        - neofetch

    - name: Neofetch | Ensure configuration directory exists
      file:
        path: "{{ ansible_facts.env.HOME }}/.config/neofetch"
        state: directory
        owner: "{{ ansible_facts.env.USER }}"
        group: "{{ ansible_facts.env.USER }}"
        mode: 0755

    - name: Neofetch | Set configuration file
      copy:
        src: config.conf
        dest: "{{ ansible_facts.env.HOME }}/.config/neofetch/config.conf"
        owner: "{{ ansible_facts.env.USER }}"
        group: "{{ ansible_facts.env.USER }}"
        mode: 0644

  become: true
  tags:
    - neofetch