---
# roles/neofetch/tasks/debian.yml

- name: Setup Neofetch
  block:

    - name: Install neofetch
      apt:
        name: neofetch
        state: present
      tags:
        - neofetch

    - name: Ensure configuration directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config/neofetch"
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0755

    - name: Set configuration file
      copy:
        src: config.conf
        dest: "{{ ansible_env.HOME }}/.config/neofetch/config.conf"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0644

  become: true
  tags:
    - neofetch