---
# roles/neofetch/tasks/macos.yml

- name: Neofetch | Setup and configuration
  block:
    - name: Install neofetch
      homebrew:
        name: neofetch
        state: present

    - name: Neofetch | Ensure directory exists
      file:
        path: "{{ ansible_env.HOME }}/.config/neofetch"
        state: directory

    - name: Set configuration file
      copy:
        src: config.conf
        dest: "{{ ansible_env.HOME }}/.config/neofetch/config.conf"
        owner: "{{ ansible_env.USER }}"
        group: "staff"
        mode: '0644'
  tags:
    - neofetch