---
# These steps are based on the official Docker documentation: https://docs.docker.com/engine/install/ubuntu/#installation-methods

- name: Docker | Setup and configuration
  block:
  - name: "Docker | Update APT cache"
    apt:
      update_cache: true

  - name: Docker | Install required system packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      state: latest
      update_cache: true

  - name: Docker | Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Docker | Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Docker | Update apt and install docker-ce
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose
      state: latest
      update_cache: true

  - name: Docker | Install Docker Module for Python
    pip:
      name: docker

  become: true
  tags:
    - docker