---
# These steps are based on the official Docker documentation: https://docs.docker.com/engine/install/ubuntu/#installation-methods

- name: "Docker | Update APT cache"
  apt:
    update_cache: true
  become: true

- name: "Docker | Install dependencies"
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true
  become: true

# Add Docker’s official GPG key using get_url
- name: "Docker | Add Docker’s official GPG key"
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker.gpg
    mode: '0644'
    owner: root
    group: root
    validate_certs: yes
  become: true

- name: "Docker | Get System Architecture"
  command: "dpkg --print-architecture"
  register: dpkg_architecture
  changed_when: false
  failed_when: false
  check_mode: false

- name: "Docker | Add Docker’s stable repository"
  apt_repository:
    repo: >-
      deb [arch={{ dpkg_architecture.stdout }} signed-by=/usr/share/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable
    filename: docker
    mode: '0644'
    update_cache: true
  become: true

- name: "Docker | Install Docker Engine"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: "Docker | Enable service"
  systemd:
    enabled: true
    name: docker
    state: started
  become: true
  when: not ansible_host_environment_is_wsl

- name: "Docker | Add to group"
  user:
    append: true
    groups: docker
    name: "{{ ansible_env.USER }}"
  become: true

- name: "Docker | Ensure docker data directory exists"
  file:
    path: "{{ ansible_env.HOME }}/.local/lib/docker"
    state: directory
    mode: '0710'
  become: true

- name: "Docker | Copy daemon.json"
  template:
    dest: "/etc/docker/daemon.json"
    src: "daemon.json"
    mode: '0644'
  become: true
  notify: restart_docker