---
# roles/docker/tasks/debian.yml

- name: Check if Docker is already installed
  stat:
    path: "/usr/bin/docker"
  register: docker_installed
  tags:
    - docker

- name: Install Docker
  block:
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create directory for Docker GPG keyring
      file:
        path: "/etc/apt/keyrings"
        state: directory
        mode: 0755

    - name: Add Docker's official GPG key
      get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: "/etc/apt/keyrings/docker.gpg"
        mode: 0644

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: "docker"

    - name: Update APT cache after adding Docker repository
      apt:
        update_cache: true

    - name: Install Docker and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes

  become: true
  when: not docker_installed.stat.exists
  tags:
    - docker