---
# roles/docker/tasks/debian.yml

- name: Check if Docker is already installed
  state:
    path: "/usr/bin/docker"
  register: docker_installed
  tags:
    - docker

- name: Install Docker
  block:
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
      state: present

  - name: Update APT cache after adding Docker repository
    apt:
      update_cache: yes

  - name: Install Docker and related packages
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present

  - name: Add user to Docker group
    user:
      name: "{{ ansible_user | default('your_username') }}"
      groups: docker
      append: yes

  when: not docker_installed.stat.exists
  tags:
    - docker