---
# roles/htop/tasks/debian.yml

- name: Htop | Setup and configure
  block:

    - name: Htop | Install via Apt
      apt:
        name: htop
        state: present

    - name: Htop | Ensure config directory exists
      file:
        path: "{{ ansible_facts.env.HOME }}/.config/htop"
        state: directory
        owner: "{{ ansible_facts.env.USER }}"
        group: "{{ ansible_facts.env.USER }}"
        mode: 0755

    - name: Htop | Copy configuration file
      copy:
        src: htoprc
        dest: "{{ ansible_facts.env.HOME }}/.config/htop/htoprc"
        owner: "{{ ansible_facts.env.USER }}"
        group: "{{ ansible_facts.env.USER }}"
        mode: '0644'
        directory_mode: '0755'
        force: true

  become: true
  tags:
    - htop
