---
# roles/htop/tasks/macos.yml

- name: Htop | Install via Homebrew
  homebrew:
    name: htop
    state: present
  tags:
    - htop

- name: Htop | Ensure config directory exists
  file:
    path: "{{ ansible_facts.env.HOME }}/.config/htop"
    state: directory
    owner: "{{ ansible_facts.env.USER }}"
    group: "staff"
    mode: 0755
  tags:
    - htop

- name: Htop | Copy configuration file
  copy:
    src: htoprc
    dest: "{{ ansible_facts.env.HOME }}/.config/htop/htoprc"
    owner: "{{ ansible_facts.env.USER }}"
    group: "staff"
    mode: 0644
    directory_mode: 0755
    force: true
  tags:
    - htop
