---
# roles/starship/tasks/debian.yml

- name: Starship | Setup and configuration
  block:
    - name: Starship | Download dependencies
      apt:
        name: snapd
        update_cache: true
    
    - name: Starship | Install Starship using Snap
      community.general.snap:
        name: starship
        channel: edge
        state: present

    - name: Starship | Copy configuration file
      copy:
        src: "starship.toml"
        dest: "{{ ansible_env.HOME }}/.config"
        mode: 0644
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"

    # Adding to the zshrc will be done in the finalize_zshrc to ensure it's EOF plaement.
  become: true
  tags:
    - starship