---
# roles/starship/tasks/debian.yml

- name: Setup Starship
  block:

    - name: Install starship
      apt:
        name: starship
        state: present
      when: ansible_os_family == "Debian"
      tags:
        - starship

    - name: Copy configuration file
      copy:
        src: "starship.toml"
        dest: "{{ ansible_env.HOME }}/.config"
        mode: 0644
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"

    # Adding to the zshrc will be done in the finalize_zshrc to ensure it's EOF plaement.
  
  become: true
  tags:
    - starship