---
# roles/starship/macos.yml

- name: Starship | Install via Homebrew
  homebrew:
    name: starship
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - starship

- name: Starship | Copy configuration file
  copy:
    src: "starship.toml"
    dest: "{{ ansible_env.HOME }}/.config"
    mode: 0644
    owner: "{{ ansible_env.USER }}"
    group: "staff"
  tags:
    - starship