---
# roles/starship/tasks/main.yml

- name: MacOSX | Install via Homebrew
  homebrew:
    name: starship
    state: present
  when: ansible_os_family == "Darwin"
  tags:
    - starship

- name: Linux | Debian-based | Install via Apt
  apt:
    name: starship
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - starship

- name: Add aliases with blank line before the block
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      # Starship
      eval "$(starship init zsh)"
    insertafter: EOF
  tags:
    - starship