---
# roles/alacritty/tasks/linux.yml

- name: Install Alacritty via apt
  apt:
    name: alacritty
    state: present
  tags:
    - alacritty

- name: Ensure Alacritty config and themes directories exist
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty/themes"
    state: directory
    mode: '0755'
  tags:
    - alacritty

- name: Copy Alacritty configuration file
  copy:
    src: alacritty.toml
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  tags:
    - alacritty

- name: Clone Alacritty Themes repository
  git:
    repo: 'https://github.com/alacritty/alacritty-theme.git'
    dest: "{{ ansible_env.HOME }}/.config/alacritty/themes"
    version: main
    force: yes
  tags:
    - alacritty