---
# roles/alacritty/tasks/macos.yml


- name: Alacritty | Install via Homebrew
  homebrew:
    name: alacritty
    state: present
  tags:
    - alacritty

- name: Alacritty | Check if themes repository exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/alacritty/themes/.git"
  register: alacritty_repo_exists
  tags:
    - alacritty

- name: Alacritty | Clone Alacritty themes repository
  git:
    repo: "https://github.com/alacritty/alacritty-theme.git"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/themes"
  when: not alacritty_repo_exists.stat.exists
  tags:
    - alacritty

- name: Alacritty | Pull latest changes from themes repository
  git:
    repo: "https://github.com/alacritty/alacritty-theme.git"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/themes"
    update: yes
  when: alacritty_repo_exists.stat.exists
  tags:
    - alacritty

- name: Alacritty | Copy configuration file (MacOS)
  copy:
    src: alacritty.toml
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.toml"
    owner: "{{ ansible_env.USER }}"
    group: "staff"
    mode: 0644
  tags:
    - alacritty

- name: Alacritty | Add to doc
  set_fact:
    dockitems_persist: "{{ dockitems_persist + [ { 'name': 'Alacritty', 'path': '/Applications/Alacritty.app', 'pos': '5' } ] }}"