---
# roles/alacritty/tasks/main.yml

- name: Load install playbook
  include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  tags:
    - alacritty

- name: Load install playbook
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"
  tags:
    - alacritty