---
# roles/btop/tasks/macos.yml

- name: Btop | Install via Homebrew
  homebrew:
    name: btop
    state: present
  tags:
    - btop

- name: Btop | Ensure config directory exists
  file:
    path: "{{ ansible_facts.env.HOME }}/.config/btop"
    state: directory
    owner: "{{ ansible_facts.env.USER }}"
    group: "staff"
    mode: 0755
  tags:
    - btop

- name: Btop | Copy configuration file
  copy:
    src: btop.conf
    dest: "{{ ansible_facts.env.HOME }}/.config/btop/btop.conf"
    owner: "{{ ansible_facts.env.USER }}"
    group: "staff"
    mode: 0644
    directory_mode: 0755
    force: true
  tags:
    - btop
