set-option -sa terminal-overrides ",xterm*:Tc"
set -g base-index 1              # Start indexing windows at 1 instead of 0
set -g pane-base-index 1         # Same for panes
setw -g pane-base-index 1        # Same for panes
set -g renumber-windows on       # Re-index windows when a window is closed
set -g history-limit 1000000     # Set history limit to 1000000
set -g mode-keys vi              # Set vi mode
set -g status-interval 1

# Easy reload config
bind r source-file ~/.config/tmux/tmux.conf

# Kill session
# bind -n k kill-session

# Keybindings for pane resize
# Navigation inside copy-mode-vi
bind-key -T copy-mode-vi j cursor-left
bind-key -T copy-mode-vi i cursor-up
bind-key -T copy-mode-vi k cursor-down
bind-key -T copy-mode-vi l cursor-right

# Word-wise jumps
bind-key -T copy-mode-vi C-j back-word      # Jump to previous word
bind-key -T copy-mode-vi C-l next-word      # Jump to next word
bind-key -T copy-mode-vi C-i cursor-up      # Jump to line start
bind-key -T copy-mode-vi C-k cursor-down    # Jump to line end

# Half-page scrolling
bind-key -T copy-mode-vi C-u halfpage-up
bind-key -T copy-mode-vi C-o halfpage-down

bind-key -n Home send Escape "OH"                    # Fix Home Key
bind-key -n End send Escape "OF"                     # Fix End  Key

# Bind dev session
bind S source-file ~/.config/tmux/dev.conf

# Plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux/fzf'
set -g @sessionx-zoxide-mode 'on'
