---
# roles/bat/tasks/debian.yml

- name: Install via Apt
  apt:
    name: bat
    state: present
  become: true
  tags:
    - bat

- name: Add aliases
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      # Bat
      alias cat=bat
  tags:
    - bat