---
# roles/bat/tasks/debian.yml

- name: Bat
  block:
    - name: Bat | Install via Apt
      apt:
        name: bat
        state: present

    - name: Bat | Add aliases
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: |
          # Bat
          alias cat=bat

  become: true
  tags:
    - bat