---
# roles/bat/tasks/macos.yml

- name: Bat | Install via Homebrew
  homebrew:
    name: bat
    state: present
  tags:
    - bat

- name: Bat | Add aliases
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      # Bat
      alias cat=bat
  tags:
    - starship