---
# roles/fonts/tasks/debian.yml

- name: Fonts | Setup and configuration
  block:
    - name: Fonts | Ensure fonts directory exists
      file:
        path: "{{ ansible_env.HOME }}/local/share/.fonts"
        state: directory

    - name: Fonts | Download and install Nerd Fonts
      unarchive:
        src: "{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/.local/share/fonts"
        remote_src: yes
      loop:
        - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
        - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip
        - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Meslo.zip
        - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/NerdFontsSymbolsOnly.zip
 
  become: true
  tags:
    - fonts