---
# roles/fonts/tasks/debian.yml

- name: Fonts | Setup and configuration
  block:
    - name: Fonts | Ensure fonts directory exists
      file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory

    - name: Fonts | Download and install Nerd Fonts
      unarchive:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/.local/share/fonts"
        remote_src: yes
      loop: "{{ fonts }}"
 
  become: true
  tags:
    - fonts